sudo: required
services:
  - docker

before_install:
  - docker build -t callrua/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true callrua/react-test npm test

after_success:
  - docker build -t callrua/multi-client ./client
  - docker build -t callrua/multi-nginx ./nginx
  - docker build -t callrua/multi-server ./server
  - docker build -t callrua/multi-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker Hub
  - docker push callrua/multi-client 
  - docker push callrua/multi-nginx
  - docker push callrua/multi-server
  - docker push callrua/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: "elasticbeanstalk-eu-west-1-908244853628"
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
